#ifndef MAXWELL_PARAMETERS_H
#define MAXWELL_PARAMETERS_H

#include <parameters.h>

#include <string>

// DO NOT MODIFY - This file is automatically generated during compilation.

class MaxwellParameters : public Parameters {
  public:
    MaxwellParameters() : Parameters(1){
      mGridPoints = 101;
      mGaussianSigma = 0.125;
    }

    inline void setGridPoints(int GridPoints){
      mGridPoints = GridPoints;
    }

    inline int getGridPoints(){
      return mGridPoints;
    }

    inline void setGaussianSigma(double GaussianSigma){
      mGaussianSigma = GaussianSigma;
    }

    inline double getGaussianSigma(){
      return mGaussianSigma;
    }

  private:
    int mGridPoints;
    double mGaussianSigma;
};

#endif
