#ifndef MAXWELL_PARSER_H
#define MAXWELL_PARSER_H

#include <paramparser.h>
#include <maxwellparameters.h>

// DO NOT MODIFY - This file is automatically generated during compilation.

class MaxwellParser : ParamParser{
  public:
    MaxwellParser() : ParamParser(1){}

    virtual ~MaxwellParser(){}

    virtual void updateParameters(std::string fname, Parameters* params);
};

#endif
