#include <maxwellparser.h>
#include <iostream>

using namespace std;

// DO NOT MODIFY - This file is automatically generated during compilation.

void MaxwellParser::updateParameters(string fname, Parameters* params){
  if(!checkId(params)){
    return;
  }
  reader.clearData();
  ParamReader::ParamResult result = reader.readFile(fname);
  if(result != ParamReader::SUCCESS){
    cout << "An error occurred while trying to read " << fname << ".\n";
    return;
  }
  MaxwellParameters *pars = (MaxwellParameters*) params;

  if(!reader.hasSection(string("Maxwell"))){
    return;
  }

  if(reader.hasParameter(string("Maxwell"),string("GridPoints"))){
    int result = reader.readAsInt(string("Maxwell"),string("GridPoints"));
    if(result <= 128000 && result >= 7){
      pars->setGridPoints(result);
    }
    else{
      cout << "Parameter GridPoints out of range.\n";
    }
  }

  if(reader.hasParameter(string("Maxwell"),string("GaussianSigma"))){
    double result = reader.readAsDouble(string("Maxwell"),string("GaussianSigma"));
    if(result <= 1.000000e+06 && result >= 1.000000e-03){
      pars->setGaussianSigma(result);
    }
    else{
      cout << "Parameter GaussianSigma out of range.\n";
    }
  }

}

